[tool.poetry]
name = "fastapi-mlflow"
version = "0.1.0"
description = "Deploy mlflow models as JSON APIs with minimal new code."
authors = ["John Harrison <john.harrison@autotrader.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
mlflow = "^1.23.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
darker = "^1.3.2"
flake8-bugbear = "^22.1.11"
isort = "^5.10.1"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
